# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzHRyI3a24KF7h77NZR6DCgFT-QVhd7s
"""

from pyspark.sql import SparkSession
from pyspark.sql.functions import col, expr, mean, corr

spark=SparkSession.builder.appName("Moda").getOrCreate()

spark

df=spark.read.csv("na.csv", header=True, inferSchema=True, sep=";")

df.show()

df_moda=df.groupBy("Notas").count().orderBy("count", ascending=False).first()
moda_valor=df_moda["Notas"]
moda_conteo=df_moda["count"]

print(f"Moda: {moda_valor} (aparece {moda_conteo} veces)")